Authentication/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'story9'

urlpatterns = [
    path('', auth_views.LoginView.as_view(template_name="index.html"), name='index'),
    path('login/', auth_views.LoginView.as_view(template_name="login.html", redirect_authenticated_user=True), name="login"),
    path('logout/', auth_views.LogoutView.as_view(template_name="logout.html"), name="logout"),
    path('profile/', views.profile, name='profile')
]

story9/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('', include('Authentication.urls')),
    path('admin/', admin.site.urls),
]

Authentication/models.py
from django.db import models

# Create your models here.

Authentication/forms.py
from django import forms

class loginForm(forms.Form):

    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'type' : 'text',
        'placeholder': "Enter your username",
        'required': True,
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'type' : 'password',
        'placeholder': "Enter your password",
        'required': True,
    }))

Authentication/views.py
# Create your views here.
from django.http import HttpResponse
from django.shortcuts import render, redirect
from .forms import loginForm
from django.contrib.auth import authenticate, login, logout


# Create your views here.
def index(request):
    form = loginForm(request.POST or None)
    flag = False
    if request.method == "POST":
        form = loginForm(request.POST)
        if form.is_valid():
            uname = form.cleaned_data['username']
            passw = form.cleaned_data['password']
            user = authenticate(request, username=uname, password=passw)
            if user is not None:
                login(request, user)
                flag = True
                response = {'form':form,'user':user,'flag':flag}
                return redirect('index')
            else:
                response = {'form':form,'user':user,'flag':flag}
                return redirect('index')
    else:
        response = {'form':form}
        return render(request,'index.html',response)

def logout_view(request):
    logout(request)
    form = loginForm()
    response = {'form':form}
    return redirect('')

def profile(request):
    return render(request, 'profile.html', {'user':request.user})

Authentication/templates/index.html
{% load static %}

<html lang="en">
<head>

    <meta charset="UTF-8">
    <!-- Font Awesome Icons -->
    <link href="{% static 'css/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Merriweather+Sans:400,700" rel="stylesheet">
    <link href='https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic' rel='stylesheet' type='text/css'>

    <!-- Plugin CSS -->
    <link href="{% static 'css/vendor/magnific-popup/magnific-popup.css' %}" rel="stylesheet">

    <title>Story 9</title>

    <!-- Theme CSS - Includes Bootstrap -->
    <link href="{% static 'css/creative.min.css' %}" rel="stylesheet">
  
    <link href="{% static 'css/style.css' %}" rel="stylesheet"> 
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}" >
    <link rel="stylesheet" type="text/css" href="{% static 'story/style.css' %}">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js" integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU=" crossorigin="anonymous"></script>
    <script src="{% static 'js/javascript.js' %}"></script>
</head>

<body>

    {% if user.is_authenticated %}

    <h1 class='judul'>Login Successfully</h1>

    <div class="content">
        {{user.username}}
    </div>
    <div class="centre-items tombol">
        <a class='btn btn-primary tombol' href="{% url 'story9:logout' %}">logout</a>
    </div>
    {% else %}

    <h1 class='judul'>Hi, Welcome To My Life</h1>

    <div class='form'>
        <form action="profile/" method="POST">
            {% csrf_token %} 
            {{ form }}
            <div class="centre-items tombol">
                <input type="submit" class="btn btn-primary" value="Login" id="submit">
            </div>
        </form>
    </div>

    {% endif %}

</body>
</html>

Authentication/templates/logout.html
{% load static %}

<html lang="en">
<head>

    <meta charset="UTF-8">
    <!-- Font Awesome Icons -->
    <link href="{% static 'css/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Merriweather+Sans:400,700" rel="stylesheet">
    <link href='https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic' rel='stylesheet' type='text/css'>

    <!-- Plugin CSS -->
    <link href="{% static 'css/vendor/magnific-popup/magnific-popup.css' %}" rel="stylesheet">

    <title>Story 9</title>

    <!-- Theme CSS - Includes Bootstrap -->
    <link href="{% static 'css/creative.min.css' %}" rel="stylesheet">
  
    <link href="{% static 'css/style.css' %}" rel="stylesheet"> 
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}" >
    <link rel="stylesheet" type="text/css" href="{% static 'story/style.css' %}">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js" integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU=" crossorigin="anonymous"></script>
    <script src="{% static 'js/javascript.js' %}"></script>
</head>

<body>

    {% if user.is_authenticated %}

    <h1 class='judul'>Logout Successfully 
        {{user.username}}</h1>

    <div class="content">
    </div>
    <div class="centre-items tombol">
        <a class='btn btn-primary tombol' href="{% url 'story9:index' %}">logout</a>
    </div>
    {% else %}

    <h1 class='judul'>Logout Successfully!</h1>
    <h3>Selamat anda telah keluar dari halaman saya ini</h3>

    <div class='form'>
        <form action="{% url 'story9:index' %}" method="POST">
            {% csrf_token %} {{ form }}
            <div class="centre-items tombol">
                <input type="submit" class="btn btn-primary" value="Home" id="submit">
            </div>
        </form>
    </div>

    {% endif %}

</body>
</html>

Authentication/templates/profile.html
{% load static %}

<html lang="en">
<head>

    <meta charset="UTF-8">
    <!-- Font Awesome Icons -->
    <link href="{% static 'css/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Merriweather+Sans:400,700" rel="stylesheet">
    <link href='https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic' rel='stylesheet' type='text/css'>

    <!-- Plugin CSS -->
    <link href="{% static 'css/vendor/magnific-popup/magnific-popup.css' %}" rel="stylesheet">

    <title>Story 9</title>

    <!-- Theme CSS - Includes Bootstrap -->
    <link href="{% static 'css/creative.min.css' %}" rel="stylesheet">
  
    <link href="{% static 'css/style.css' %}" rel="stylesheet"> 
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}" >
    <link rel="stylesheet" type="text/css" href="{% static 'story/style.css' %}">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js" integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU=" crossorigin="anonymous"></script>
    <script src="{% static 'js/javascript.js' %}"></script>
</head>

<body>

    {% if user.is_authenticated %}

    <h1 class='judul'>Login Successfully 
        {{user.username}}</h1>

    <div class="content">
    </div>
    <div class="centre-items tombol">
        <a class='btn btn-primary tombol' href="{% url 'story9:logout' %}">logout</a>
    </div>
    {% else %}

    <h1 class='judul'>Welcome, Marcel!</h1>
    <h3>Apa yang anda lakukan di website saya ini? Jika gabut tekan tombol logout</h3>

    <div class='form'>
        <form action="{% url 'story9:logout' %}" method="POST">
            {% csrf_token %} {{ form }}
            <div class="centre-items tombol">
                <input type="submit" class="btn btn-primary" value="Logout" id="submit">
            </div>
        </form>
    </div>

    {% endif %}

</body>
</html>